version: "3.7"
services:

  spark-master:
    image: docker.io/bitnami/spark:3.1
    container_name: spark-master
    user: root # This parameter is key to let spark write on volumes
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./apps/spark:/opt/spark-apps:rw
      - ./data/spark:/opt/spark-data:rw
      #- /mnt/c/Users/asanturi/.m2/repository/com:/opt/spark-libraries/
      - ./libraries/com:/opt/spark-libraries/
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MODE=master"
      - "SPARK_RPC_AUTHENTICATION_ENABLED=no"
      - "SPARK_RPC_ENCRYPTION_ENABLED=no"
      - "SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no"
      - "SPARK_SSL_ENABLED=no"



  spark-worker:
    image: docker.io/bitnami/spark:3.1
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
      - "SPARK_RPC_AUTHENTICATION_ENABLED=no"
      - "SPARK_RPC_ENCRYPTION_ENABLED=no"
      - "SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no"
      - "SPARK_SSL_ENABLED=no"
    volumes:
      - ./apps/spark:/opt/spark-apps
      - ./data/spark:/opt/spark-data


  spark-worker-2:
    image: docker.io/bitnami/spark:3.1
    container_name: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
      - "SPARK_RPC_AUTHENTICATION_ENABLED=no"
      - "SPARK_RPC_ENCRYPTION_ENABLED=no"
      - "SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no"
      - "SPARK_SSL_ENABLED=no"
    volumes:
      - ./apps/spark:/opt/spark-apps
      - ./data/spark:/opt/spark-data

# For the moment being, zeppeling not correctly implemented
#
#  zeppelin:
#    image: apache/zeppelin:0.9.0
#    container_name: zeppelin-compose
#    ports:
#      - "9090:8080"
#    volumes:
#      - /mnt/c/Users/asanturi/Documents/test/spark:/zeppelin/spark
#      - ./apps/zeppelin:/opt/zeppelin-apps
#    #  - ./data/zeppelin:/opt/zeppelin-data
#      - ./data/zeppelin/notebooks:/opt/zeppelin-notebooks
#      - ./logs:/logs
#      - ./notebooks:/notebooks
#    #  - ./conf/interpreter.json:/zeppelin/conf/interpreter.json
#    #  - /mnt/c/Users/asanturi/Documents/zeppelin-standalone/spark3:/opt/spark
#
#
#    environment:
#      - "ZEPPELIN_NOTEBOOK_DIR=/opt/zeppelin-notebooks"
#      - "ZEPPELIN_LOG_DIR:/logs"
#      - "SPARK_HOME=/zeppelin/spark"
#     - "SPARK_LOCAL_IP=spark-master"
#      - "SPARK_MASTER=spark://4a7ccfd6da3e:7077"
#      - "MASTER=spark://4a7ccfd6da3e:7077"
#      - "ZEPPELIN_SSL=false"
#      - "ZEPPELIN_SSL_CLIENT_AUTH=false"
#      - "ZEPPELIN_LOCAL_IP=0.0.0.0"

